steps:
  # Build docker image using pom.xml jib config
  - name: gcr.io/cloud-builders/mvn
    args: ['compile', '-Pproduction', 'jib:build']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'alpha',
            'run',
            'deploy',
            'vaadin-test',
            '--project', 'wmix-desenvolvimento',
            '--region', 'us-central1',
            '--min-instances', '0',
            '--max-instances', '1',
            '--cpu', '1',
            '--memory', '256Mi',
            '--timeout', '30s',
            '--cpu-throttling',
            '--cpu-boost',
            '--port', '8080',
            '--allow-unauthenticated',
            '--session-affinity',
            '--no-traffic',
            '--image', 'us-central1-docker.pkg.dev/wmix-desenvolvimento/apps/vaadin-test:$TAG_NAME' ]